name: Python CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Xvfb
      run: sudo apt-get install -y xvfb

    - name: Run Xvfb
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1024x768x16 &

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        export DISPLAY=:99
        python -m unittest discover -s test -p "*.py"
